'use client';
import * as React from 'react';
import type { RefObject } from '@mui/x-internals/types';
import useLazyRef from '@mui/utils/useLazyRef';
import { isObjectEmpty } from '@mui/x-internals/isObjectEmpty';
import type { GridEventListener } from '../../../models/events';
import type { DataGridProcessedProps } from '../../../models/props/DataGridProps';
import type { GridPrivateApiCommunity } from '../../../models/api/gridApiCommunity';
import type {
  GridRowApi,
  GridRowProApi,
  GridRowProPrivateApi,
} from '../../../models/api/gridRowApi';
import type { GridRowId, GridGroupNode, GridLeafNode } from '../../../models/gridRows';
import { useGridApiMethod } from '../../utils/useGridApiMethod';
import { useGridLogger } from '../../utils/useGridLogger';
import {
  gridRowCountSelector,
  gridRowsLookupSelector,
  gridRowTreeSelector,
  gridRowGroupingNameSelector,
  gridRowTreeDepthsSelector,
  gridDataRowIdsSelector,
  gridRowMaximumTreeDepthSelector,
  gridRowGroupsToFetchSelector,
  gridRowNodeSelector,
  gridDataRowsSelector,
} from './gridRowsSelector';
import { gridRowIdSelector } from '../../core/gridPropsSelectors';
import { useTimeout } from '../../utils/useTimeout';
import { GridSignature } from '../../../constants/signature';
import { useGridEvent } from '../../utils/useGridEvent';
import type { GridStateInitializer } from '../../utils/useGridInitializeState';
import { getVisibleRows } from '../../utils/useGridVisibleRows';
import { gridSortedRowIdsSelector } from '../sorting/gridSortingSelector';
import { gridFilteredRowsLookupSelector } from '../filter/gridFilterSelector';
import type { GridRowsInternalCache } from './gridRowsInterfaces';
import {
  getTreeNodeDescendants,
  createRowsInternalCache,
  getRowsStateFromCache,
  isAutogeneratedRowNode,
  GRID_ROOT_GROUP_ID,
  GRID_ID_AUTOGENERATED,
  updateCacheWithNewRows,
  getTopLevelRowCount,
  getRowIdFromRowModel,
  computeRowsUpdates,
} from './gridRowsUtils';
import { useGridRegisterPipeApplier } from '../../core/pipeProcessing';
import { GridStrategyGroup } from '../../core/strategyProcessing';
import { gridPivotActiveSelector } from '../pivoting';
import type { GridConfiguration } from '../../../models/configuration/gridConfiguration';

export const rowsStateInitializer: GridStateInitializer<
  Pick<DataGridProcessedProps, 'dataSource' | 'rows' | 'rowCount' | 'getRowId' | 'loading'>
> = (state, props, apiRef) => {
    throw new Error("STUB");
};

export const useGridRows = (
  apiRef: RefObject<GridPrivateApiCommunity>,
  props: Pick<
    DataGridProcessedProps,
    | 'rows'
    | 'getRowId'
    | 'rowCount'
    | 'throttleRowsMs'
    | 'signature'
    | 'pagination'
    | 'paginationMode'
    | 'loading'
    | 'dataSource'
    | 'processRowUpdate'
    | 'onProcessRowUpdateError'
  >,
  configuration: GridConfiguration,
): void => {
  if (process.env.NODE_ENV !== 'production') {
    try {
      // Freeze the `rows` prop so developers have a fast failure if they try to use Array.prototype.push().
      Object.freeze(props.rows);
    } catch (error) {
      // Sometimes, it's impossible to freeze, so we give up on it.
    }
  }

  const logger = useGridLogger(apiRef, 'useGridRows');

  const lastUpdateMs = React.useRef(Date.now());
  const lastRowCount = React.useRef(props.rowCount);
  const timeout = useTimeout();

  // Get overridable methods from configuration
  const { setRowIndex, setRowPosition } = configuration.hooks.useGridRowsOverridableMethods(
    apiRef,
    props as DataGridProcessedProps,
  );

  const getRow = React.useCallback<GridRowApi['getRow']>(
    (id) => {
          throw new Error("STUB");
      },
    [apiRef],
  );

  const getRowId = React.useCallback<GridRowApi['getRowId']>(
    (row) => { throw new Error("STUB"); },
    [apiRef],
  );

  const throttledRowsChange = React.useCallback(
    ({ cache, throttle }: { cache: GridRowsInternalCache; throttle: boolean }) => {
          throw new Error("STUB");
      },
    [props.throttleRowsMs, props.rowCount, props.loading, apiRef, timeout],
  );

  /**
   * API METHODS
   */
  const setRows = React.useCallback<GridRowApi['setRows']>(
    (rows) => {
          throw new Error("STUB");
      },
    [
      logger,
      props.getRowId,
      props.dataSource,
      props.loading,
      props.rowCount,
      throttledRowsChange,
      apiRef,
    ],
  );

  const updateRows = React.useCallback<GridRowApi['updateRows']>(
    (updates) => {
          throw new Error("STUB");
      },
    [props.signature, props.dataSource, props.getRowId, throttledRowsChange, apiRef],
  );

  const updateNestedRows = React.useCallback<GridRowProPrivateApi['updateNestedRows']>(
    (updates, groupKeys) => {
          throw new Error("STUB");
      },
    [props.getRowId, throttledRowsChange, apiRef],
  );

  const setLoading = React.useCallback<GridRowApi['setLoading']>(
    (loading) => {
          throw new Error("STUB");
      },
    [apiRef, logger],
  );

  const getRowModels = React.useCallback<GridRowApi['getRowModels']>(() => {
      throw new Error("STUB");
  }, [apiRef]);

  const getRowsCount = React.useCallback<GridRowApi['getRowsCount']>(
    () => { throw new Error("STUB"); },
    [apiRef],
  );

  const getAllRowIds = React.useCallback<GridRowApi['getAllRowIds']>(
    () => { throw new Error("STUB"); },
    [apiRef],
  );

  const getRowIndexRelativeToVisibleRows = React.useCallback<
    GridRowApi['getRowIndexRelativeToVisibleRows']
  >(
    (id) => {
          throw new Error("STUB");
      },
    [apiRef],
  );

  const setRowChildrenExpansion = React.useCallback<GridRowProApi['setRowChildrenExpansion']>(
    (id, isExpanded) => {
          throw new Error("STUB");
      },
    [apiRef],
  );

  const expandAllRows = React.useCallback<GridRowProApi['expandAllRows']>(() => {
      throw new Error("STUB");
  }, [apiRef]);

  const collapseAllRows = React.useCallback<GridRowProApi['collapseAllRows']>(() => {
      throw new Error("STUB");
  }, [apiRef]);

  const getRowNode = React.useCallback<GridRowApi['getRowNode']>(
    (id) => { throw new Error("STUB"); },
    [apiRef],
  );

  const getRowGroupChildren = React.useCallback<GridRowProApi['getRowGroupChildren']>(
    ({
      skipAutoGeneratedRows = true,
      groupId,
      applySorting,
      applyFiltering,
      directChildrenOnly = false,
    }) => {
          throw new Error("STUB");
      },
    [apiRef],
  );

  const replaceRows = React.useCallback<GridRowApi['unstable_replaceRows']>(
    (firstRowToRender, newRows) => {
          throw new Error("STUB");
      },
    [apiRef, props.signature, props.getRowId, props.loading, props.rowCount],
  );

  const rowApi: GridRowApi = {
    getRow,
    setLoading,
    getRowId,
    getRowModels,
    getRowsCount,
    getAllRowIds,
    setRows,
    updateRows,
    getRowNode,
    getRowIndexRelativeToVisibleRows,
    unstable_replaceRows: replaceRows,
  };

  const rowProApi: GridRowProApi = {
    setRowIndex,
    setRowPosition,
    setRowChildrenExpansion,
    getRowGroupChildren,
    expandAllRows,
    collapseAllRows,
  };

  const rowProPrivateApi: GridRowProPrivateApi = {
    updateNestedRows,
  };

  /**
   * EVENTS
   */
  const groupRows = React.useCallback(() => {
      throw new Error("STUB");
  }, [
    logger,
    apiRef,
    props.rows,
    props.getRowId,
    props.loading,
    props.rowCount,
    throttledRowsChange,
  ]);

  const previousDataSource = useLazyRef(() => { throw new Error("STUB"); });
  const handleStrategyProcessorChange = React.useCallback<
    GridEventListener<'activeStrategyProcessorChange'>
  >(
    (methodName) => {
          throw new Error("STUB");
      },
    [groupRows, previousDataSource, props.dataSource],
  );

  const handleStrategyActivityChange = React.useCallback<
    GridEventListener<'strategyAvailabilityChange'>
  >(() => {
      throw new Error("STUB");
  }, [apiRef, groupRows]);

  useGridEvent(apiRef, 'activeStrategyProcessorChange', handleStrategyProcessorChange);
  useGridEvent(apiRef, 'strategyAvailabilityChange', handleStrategyActivityChange);

  /**
   * APPLIERS
   */
  const applyHydrateRowsProcessor = React.useCallback(() => {
      throw new Error("STUB");
  }, [apiRef, props.rowCount]);

  useGridRegisterPipeApplier(apiRef, 'hydrateRows', applyHydrateRowsProcessor);

  useGridApiMethod(apiRef, rowApi, 'public');
  useGridApiMethod(
    apiRef,
    rowProApi,
    props.signature === GridSignature.DataGrid ? 'private' : 'public',
  );
  useGridApiMethod(apiRef, rowProPrivateApi, 'private');

  // The effect do not track any value defined synchronously during the 1st render by hooks called after `useGridRows`
  // As a consequence, the state generated by the 1st run of this useEffect will always be equal to the initialization one
  const isFirstRender = React.useRef(true);
  React.useEffect(() => {
      throw new Error("STUB");
  }, [
    props.rows,
    props.rowCount,
    props.getRowId,
    props.loading,
    props.dataSource,
    logger,
    throttledRowsChange,
    apiRef,
  ]);
};
